# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_signup_pan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='fullname',
        ),
        migrations.AddField(
            model_name='signup',
            name='first_name',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='signup',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
    ]
