# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-20 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_signup_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='date_of_birth',
            field=models.DateTimeField(),
        ),
    ]
